import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import express, { Request, Response } from "express";
import { z } from "zod";

const server = new McpServer({
  name: "neuro-mcp-agent",
  version: "1.0.0",
});

// Tool 1: Search Neuroscience Papers from arXiv
server.registerTool(
  "search_papers",
  {
    title: "Search Neuroscience Papers",
    description: "Search neuroscience research papers from arXiv",
    inputSchema: {
      query: z.string().describe("Search query, e.g. 'memory consolidation hippocampus'"),
    },
  },
  async ({ query }) => {
    const url = `https://export.arxiv.org/api/query?search_query=all:${encodeURIComponent(query)}&cat=q-bio.NC&max_results=5`;
    const response = await fetch(url);
    const text = await response.text();

    const titles = [...text.matchAll(/<title>(.*?)<\/title>/gs)].slice(1).map(m => m[1].trim());
    const abstracts = [...text.matchAll(/<summary>(.*?)<\/summary>/gs)].map(m => m[1].trim().slice(0, 200));
    const links = [...text.matchAll(/<id>(.*?)<\/id>/gs)].slice(1).map(m => m[1].trim());

    let result = `Found ${titles.length} papers for: "${query}"\n\n`;
    titles.forEach((title, i) => {
      result += `📄 ${i + 1}. ${title}\n`;
      result += `🔗 ${links[i] || "N/A"}\n`;
      result += `📝 ${abstracts[i] || "N/A"}...\n\n`;
    });

    return { content: [{ type: "text", text: result }] };
  }
);

// Tool 2: Summarize a Paper by arXiv ID
server.registerTool(
  "summarize_paper",
  {
    title: "Summarize Paper",
    description: "Get summary of a neuroscience paper by arXiv ID",
    inputSchema: {
      arxiv_id: z.string().describe("arXiv paper ID, e.g. '2301.12345'"),
    },
  },
  async ({ arxiv_id }) => {
    const url = `https://export.arxiv.org/api/query?id_list=${arxiv_id}`;
    const response = await fetch(url);
    const text = await response.text();

    const titleMatch = text.match(/<title>(.*?)<\/title>/s);
    const abstractMatch = text.match(/<summary>(.*?)<\/summary>/s);
    const authorsMatches = [...text.matchAll(/<name>(.*?)<\/name>/g)];

    const title = titleMatch ? titleMatch[1].trim() : "Not found";
    const abstract = abstractMatch ? abstractMatch[1].trim() : "Not found";
    const authors = authorsMatches.map(m => m[1].trim()).join(", ");

    const result = `📄 Title: ${title}\n\n👥 Authors: ${authors}\n\n📝 Abstract:\n${abstract}`;
    return { content: [{ type: "text", text: result }] };
  }
);

// Tool 3: Generate Python Analysis Code
server.registerTool(
  "generate_analysis_code",
  {
    title: "Generate Analysis Code",
    description: "Generate Python code for neuroscience data analysis",
    inputSchema: {
      analysis_type: z.string().describe("Type of analysis, e.g. 'EEG spike detection', 'fMRI preprocessing'"),
    },
  },
  async ({ analysis_type }) => {
    const code = `# Neuroscience Analysis: ${analysis_type}
# Generated by NeuroMCP Agent

import numpy as np
import matplotlib.pyplot as plt

def analyze_${analysis_type.toLowerCase().replace(/\s+/g, '_')}(data):
    """
    Perform ${analysis_type} analysis on neural data.
    
    Parameters:
    -----------
    data : numpy array
        Input neural recording data
    
    Returns:
    --------
    results : dict
        Analysis results
    """
    # Preprocessing
    data_normalized = (data - np.mean(data)) / np.std(data)
    
    # Analysis
    results = {
        'mean': float(np.mean(data_normalized)),
        'std': float(np.std(data_normalized)),
        'max': float(np.max(data_normalized)),
        'min': float(np.min(data_normalized)),
    }
    
    # Visualization
    plt.figure(figsize=(10, 4))
    plt.plot(data_normalized)
    plt.title(f'${analysis_type} Analysis')
    plt.xlabel('Time')
    plt.ylabel('Amplitude')
    plt.grid(True)
    plt.tight_layout()
    plt.savefig('analysis_result.png', dpi=150)
    plt.show()
    
    return results

# Example usage
if __name__ == "__main__":
    sample_data = np.random.randn(1000)
    results = analyze_${analysis_type.toLowerCase().replace(/\s+/g, '_')}(sample_data)
    print("Analysis Results:", results)
`;
    return { content: [{ type: "text", text: code }] };
  }
);

// Express Setup
const app = express();
app.use(express.json());

app.get("/health", (_req: Request, res: Response) => {
  res.status(200).json({ status: "healthy", agent: "neuro-mcp-agent" });
});

app.post("/mcp", async (req: Request, res: Response) => {
  const transport = new StreamableHTTPServerTransport({
    sessionIdGenerator: undefined,
    enableJsonResponse: true,
  });
  res.on("close", () => transport.close());
  await server.connect(transport);
  await transport.handleRequest(req, res, req.body);
});

const port = parseInt(process.env.PORT || "8080");
app.listen(port, () => {
  console.log(`✅ NeuroMCP Agent running on http://localhost:${port}`);
  console.log(`🔬 Tools: search_papers, summarize_paper, generate_analysis_code`);
});

process.on("SIGTERM", () => process.exit(0));